### ISSUE TITLE
Python Installation Problem

### ISSUE THREAD

**Issue by tyjohnnew** [wiseio/paratext#42]
I downloaded the library, went to the python folder, and did python setup.py build install but I get this error when I try to import paratext

'''
Traceback (most recent call last):
  File "test_paratext.py", line 3, in <module>
    import paratext.testing
  File "/home/tom/anaconda2/lib/python2.7/site-packages/paratext/__init__.py", line 4, in <module>
    from paratext.core import *
  File "/home/tom/anaconda2/lib/python2.7/site-packages/paratext/core.py", line 29, in <module>
    import paratext_internal as pti
  File "/home/tom/anaconda2/lib/python2.7/site-packages/paratext_internal.py", line 21, in <module>
    _paratext_internal = swig_import_helper()
  File "/home/tom/anaconda2/lib/python2.7/site-packages/paratext_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_paratext_internal')
  File "/home/tom/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /home/tom/anaconda2/lib/python2.7/site-packages/_paratext_internal.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
'''

**Comment by tyjohnnew** [comment]
Anaconda messed up my installation

**Comment by CreRecombinase** [comment]
@tyjohnnew I'm having the same problem, what did you do to fix it?

**Comment by tyjohnnew** [comment]
Remove anaconda, and then directly install paratext.
