### ISSUE TITLE
Allow 'filename' to be a unicode string

### ISSUE THREAD

**Issue by pdbaines** [wiseio/paratext#7]
Currently, `load_csv_to_pandas` fails when `filename` is a unicode string. Example given below:

```
>>> df = paratext.load_csv_to_pandas(filename="/data/featurization_data.csv", allow_quoted_newlines=True)
>>> df = paratext.load_csv_to_pandas(filename=u"/data/featurization_data.csv", allow_quoted_newlines=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext/core.py", line 309, in load_csv_to_pandas
    return pandas.DataFrame.from_items(load_csv_to_expanded_columns(filename, *args, **kwargs))
  File "/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1085, in from_items
    keys, values = lzip(*items)
TypeError: zip() argument after * must be a sequence, not generator
```

**Comment by deads** [comment]
Please see Pull Request #23

**Comment by pdbaines** [comment]
Great -- thanks! Will test out and let you know if all looks good.
