### ISSUE TITLE
Allow 'filename' to accept URI-style filenames

### ISSUE THREAD

**Issue by pdbaines** [wiseio/paratext#8]
It would be very useful if `filename` accepted URI-style filenames, in addition to standard filepaths. For example,

```
>>> df = paratext.load_csv_to_pandas(filename="/data/featurization_data.csv", allow_quoted_newlines=True)
>>> df = paratext.load_csv_to_pandas(filename="file:///data/featurization_data.csv", allow_quoted_newlines=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext/core.py", line 309, in load_csv_to_pandas
    return pandas.DataFrame.from_items(load_csv_to_expanded_columns(filename, *args, **kwargs))
  File "/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1085, in from_items
    keys, values = lzip(*items)
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext/core.py", line 284, in load_csv_to_expanded_columns
    for name, col, semantics, levels in load_raw_csv(filename, *args, **kwargs):
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext/core.py", line 227, in load_raw_csv
    loader = internal_create_csv_loader(filename, *args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext/core.py", line 117, in internal_create_csv_loader
    loader.load(filename, params)
  File "/anaconda/lib/python2.7/site-packages/paratext-0.9.1rc1-py2.7-linux-x86_64.egg/paratext_internal.py", line 251, in load
    def load(self, *args): return _paratext_internal.ColBasedLoader_load(self, *args)
RuntimeError: cannot open file 'file:///data/featurization_data.csv'
```

**Comment by deads** [comment]
Please see Pull Request #23
